apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
  labels:
    app: redis-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-client
  template:
    metadata:
      labels:
        app: redis-client
    spec:
      containers:
      - name: redis-client
        image: oneviewacr.azurecr.io/dev/redis:7-alpine-linux
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600; done"]
        env:
        - name: REDIS_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: redis-auth
              key: token
        - name: REDIS_USERNAME  
          valueFrom:
            secretKeyRef:
              name: redis-auth
              key: username
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      restartPolicy: Always